FichaTecnica/FichaTecnica/Controllers/ProjetoController.cs
using FichaTecnica.Dominio;
using FichaTecnica.Dominio.Repositorio;
using FichaTecnica.Models;
using FichaTecnica.Repositorio.EF;
using FichaTecnica.Seguranca.Filters;
using FichaTecnica.Seguranca.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FichaTecnica.Controllers
{
    [Autorizador(Roles = "Gerente")]
    public class ProjetoController : Controller
    {
        private IProjetoRepositorio dataBase = new ProjetoRepositorio();
        private IUsuarioRepositorio usuarioRepositorio = new UsuarioRepositorio();

        // GET: Projeto
        public ActionResult CadastroProjeto()
        {
            UsuarioLogado usuarioLogado = (UsuarioLogado)Session["USUARIO_LOGADO"];
            ProjetoModel model = new ProjetoModel();

            model.IdUsuario = usuarioLogado.Id;

            return View(model);
        }

        [Autorizador(Roles = "Gerente")]
        public ActionResult Salvar(ProjetoModel model)
        {
            if (ModelState.IsValid)
            {
                Projeto projeto = new Projeto()
                {
                    Nome = model.Nome,
                    Descricao = model.Descricao,
                    DataInicio = DateTime.Now
                };

                Usuario usuario = usuarioRepositorio.BuscarPorId(model.IdUsuario);
                projeto.Usuarios.Add(usuario);

                var id = dataBase.CadastrarNovoProjeto(projeto);

                return RedirectToAction("TelaInicial", "TelaInicial");

            }

            ModelState.AddModelError("INVALID_LOGIN", "Usuário ou senha inválidos.");
            return View("CadastroProjeto", model);
        }
    }
}

FichaTecnica/FichaTecnica/Views/Projeto/CadastroProjeto.cshtml
@model FichaTecnica.Models.ProjetoModel

@{
    ViewBag.Title = "Cadastro de Projeto";
}

<h2>Cadastro de Projeto</h2>

@using (Html.BeginForm("Salvar", "Projeto", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.IdUsuario)

    <div class="form-group">
        @Html.LabelFor(m => m.Nome, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(m => m.Nome, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Nome)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Descricao, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextAreaFor(m => m.Descricao, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Descricao)
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-custom">Salvar</button>
        </div>
    </div>
}