FichaTecnica/FichaTecnica/Controllers/DetalhesProjetoController.cs
using FichaTecnica.Dominio;
using FichaTecnica.Dominio.Repositorio;
using FichaTecnica.Models;
using FichaTecnica.Repositorio.EF;
using FichaTecnica.Seguranca.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FichaTecnica.Controllers
{

    public class DetalhesProjetoController : Controller
    {
        private IProjetoRepositorio dataBase = new ProjetoRepositorio();
        private IMembroRepositorio dataBaseMembro = new MembroRepositorio();
        private IUsuarioRepositorio dataBaseUsuario = new UsuarioRepositorio();
        private IComentarioRepositorio dataBaseComentario = new ComentarioRepositorio();

        [Autorizador]
        public ActionResult TelaDetalhes(int Id)
        {
            Projeto projeto = dataBase.BuscarProjetoPorId(Id);

            IList<Membro> membrosDoProjeto = dataBaseMembro.BuscarMembroPorProjeto(projeto);
            membrosDoProjeto = dataBaseMembro.BuscarCargoMembros(membrosDoProjeto);
            projeto.Membros = membrosDoProjeto;

            List<Usuario> usuarios = new List<Usuario>();

            foreach(var usuario in  projeto.Usuarios)
            {
                usuarios.Add(dataBaseUsuario.BuscarPorId(usuario.Id));
            }
               
            List<MembroDetalheProjetoModel> detalhesMembros = new List<MembroDetalheProjetoModel>();
            foreach (var membro in projeto.Membros)
            {
                MembroDetalheProjetoModel membroDetalheProjetoModel = new MembroDetalheProjetoModel(membro);
                List<LinkFork> link = dataBaseMembro.BuscarLinkMembroDoProjeto(projeto.Id,membro.Id);
                membroDetalheProjetoModel.LinksGithub = new GraficoAtividadesModel(link);
                detalhesMembros.Add(membroDetalheProjetoModel);

                List<Comentario>comentarios = dataBaseComentario.BuscarComentariosPorMembro(membroDetalheProjetoModel.Id);             
                foreach(var comentario in comentarios)
                {
                    if (comentario.Tipo == Tipo.POSITIVO)
                    {
                        membroDetalheProjetoModel.TotalComentariosPosivo++;
                    }
                    else
                        membroDetalheProjetoModel.TotalComentarioNegativo++;
                }
            }

            TelaDetalhesModel model = new TelaDetalhesModel();
            model.Projeto = projeto;
            model.Usuarios = usuarios;
            model.MembrosDoProjeto = detalhesMembros;

            return View(model);
        }
    }
}

FichaTecnica/FichaTecnica/Controllers/TelaInicialController.cs
using FichaTecnica.Dominio;
using FichaTecnica.Dominio.Repositorio;
using FichaTecnica.Models;
using FichaTecnica.Repositorio.EF;
using FichaTecnica.Seguranca.Filters;
using FichaTecnica.Seguranca.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FichaTecnica.Controllers
{
    
    public class TelaInicialController : Controller
    {
        private IProjetoRepositorio dataBase = new ProjetoRepositorio();
        private IMembroRepositorio dataBaseMember = new MembroRepositorio();

        [Autorizador]
        public ActionResult Index()
        {
            UsuarioLogado usuarioLogado = HttpContext.Session["USUARIO_LOGADO"] as UsuarioLogado;
            IList<Projeto> projetos = dataBase.BuscarProjetosDoUsuario(usuarioLogado.Id);        
            IList<Membro> membros = null;
            foreach (Projeto projeto in projetos)
            {
                membros = dataBaseMember.BuscarMembroPorProjeto(projeto);
                projeto.Membros = new List<Membro>();
                foreach (Membro membro in membros)
                {        
                    projeto.Membros.Add(membro);
                }
            }

            TelaInicialModel model = new TelaInicialModel();
            model.projetos = new List<Projeto>();
            model.projetos = projetos;

            return View("TelaInicial", (model));
        }

        [Autorizador]
        public ActionResult ProjetoDetalhe(int idProjeto)
        {
            return null;
        }
    }
}

FichaTecnica/FichaTecnica/Views/TelaInicial/TelaInicial.cshtml
    @model FichaTecnica.Models.TelaInicialModel
@{
    ViewBag.Title = "TelaInicial";
}
<html>
<head>


</head>
<body>
    <h2>Projetos</h2>

    @if ( Model == null)
    {
        <h2> Sem projetos ativos</h2>
    }
    else
    {
        <table class="table table-striped table-bordered table-hover tftable tftable th tftable tr tftable td tftable tr:hover">
            <thread>
                <tr>
                    <th style="width: 25%">Nome Projeto</th>
                    <th style="width: 25%">Quantidade Membros</th>
                    <th style="width: 25%">DataInicio</th>
                    <th style="width: 25%">Detalhes do projeto</th>
                </tr>
            </thread>
            @foreach (var projeto in Model.projetos)
            {
                <tr>
                    <td>@projeto.Nome</td>
                    @if (projeto.Membros.Count != 0)
                    {
                        <td>@projeto.Membros.Count</td>
                    }
                    else
                    {
                        <td>Não há membros</td>
                    }
                    <td>@projeto.DataInicio.ToString("dd/MM/yyyy")</td>
                    <td>
                        @using (Html.BeginForm("TelaDetalhes", "DetalhesProjeto", FormMethod.Post, null))
                    {   <input type="hidden" name="id" value="@projeto.Id">
                        <input type="submit" class="btn btn-custom col-centered" name="enviar" value="Detalhes" /> }
                </td>

                </tr>
            }
        </table>
    }

    @section Scripts {
        <script>
            $("document").ready(function() {
                $("#NomeMembro").autocomplete({
                    minLength: 3,
                    source: '@Url.Action("MembroAutoComplete", "Membro")',
                    select: function () { $("#btnProcurar").click(); }
                });
                $(".ui-helper-hidden-accessible").remove();
            });
        </script>
    }

</body>
</html>